---
- name: Converge
  hosts: all

  collections:
    - merative.spm_middleware

  tasks:
    - name: Install python3
      package:
        name: python3
        state: present

    - name: Create symlink for python3
      file:
        src: /usr/bin/python3
        dest: /usr/local/bin/python
        owner: root
        group: root
        state: link

    - name: pip self-update
      pip:
        name: pip
        executable: pip3
        state: latest
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: include weblogic
      include_role:
        name: weblogic
      vars:
        ansible_python_interpreter: /usr/bin/python3
        weblogic_version: "14.1.2.0.250911"

    - name: include ohs
      include_role:
        name: ohs
      vars:
        ansible_python_interpreter: /usr/bin/python3
        weblogic_home: "/home/oracle/Oracle/Middleware/Oracle_Home"
  vars:
    download_url: "{{ lookup('env', 'ARTIFACTORY_URL') }}/{{ lookup('env', 'ARTIFACTORY_REPO') }}/SoftwareInstallers"
    download_header: { 'X-JFrog-Art-Api': "{{ lookup('env', 'ARTIFACTORY_TOKEN') }}"}