---
- name: Download repo
  get_url:
    dest: /tmp/fprepo.zip
    url: "{{ download_url }}/{{ liberty_fp_path }}"
    headers: "{{ download_header }}"
  when: download_url is defined

- name: Create repo directory
  file:
    path: /tmp/fprepo
    state: directory

- name: Copy Liberty fixpack repo
  copy:
    src: "{{ liberty_fp_path }}"
    dest: "/tmp/fprepo.zip"
  when: download_url is not defined

- name: Extract repo
  unarchive:
    src: /tmp/fprepo.zip
    dest: /tmp/fprepo
    remote_src: yes
    creates: /tmp/fprepo/repository.config

- name: Install package
  iim_package:
    iim_path: "{{ iim_install_path }}"
    product_id: "{{ pack_id }}"
    path: "{{ liberty_install_path }}"
    repo: /tmp/fprepo
    state: present
