---
liberty_fp_path: WLP/26.0.0.3-WS-LIBERTY-ND-FP.zip
liberty_installers_path: WLP/was.repo.16002.liberty.nd.zip
liberty_pid: 26.0.3.20260309_1102
jdk_version: 21.0
jdk_installation_way: unzip
liberty_java_zip_path: Java/IBM/ibm-semeru-open-jdk_x64_linux_21.0.10.1.tar.gz
