---
- name: Converge
  hosts: all

  collections:
    - merative.spm_middleware

  vars:
    ihs_version: 9.0.5.25
    download_url: "{{ lookup('env', 'ARTIFACTORY_URL') }}/{{ lookup('env', 'ARTIFACTORY_REPO') }}/SoftwareInstallers"
    download_header: { 'X-JFrog-Art-Api': "{{ lookup('env', 'ARTIFACTORY_TOKEN') }}"}

  roles:
    - iim
    - ihs
