---
- name: Converge
  hosts: all

  collections:
    - ibm.spm_middleware

  tasks:
    - name: Install python3
      package:
        name: python3
        state: present

    - name: Create symlink for python3
      file:
        src: /usr/bin/python3
        dest: /usr/local/bin/python
        owner: root
        group: root
        state: link

    - name: pip self-update
      pip:
        name: pip
        executable: pip3
        state: latest
      vars:
        ansible_python_interpreter: /usr/bin/python3

    # - name: include weblogic
    #   include_role:
    #     name: weblogic
    #   vars:
    #     ansible_python_interpreter: /usr/bin/python3
    #     weblogic_version: "12.1.3.0.210720"

    - name: include ohs
      include_role:
        name: ohs
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ohs_version: 12.1.3.0.200412

  vars:
    artifactory_url: "https://{{ lookup('env', 'JFROG_GEO') | default('eu', true) }}.artifactory.swg-devops.com/artifactory"
