---
ihs_installer_path: WAS/9.0.5ND
ihs_installer_archive_list:
  - was.repo.90500.ihs.zip
  - was.repo.90500.plugins.zip
  - was.repo.90500.wct.zip

ihs_fp_installer_path: WAS/9.0.5Fixpacks
ihs_fp_installer_archive_list:
  - 9.0.5-WS-IHSPLG-FP024.zip
  - 9.0.5-WS-WCT-FP024.zip

ihs_pid: v90_9.0.5024.20250528_1830

ihs_java_zip_path: Java/IBM/ibm-java-sdk-8.0-8.45-linux-x64-installmgr.zip
ihs_java_pid: com.ibm.java.jdk.v8
