---
base_install_file: 'fmw_14.1.1.0.0_wls.jar'
weblogic_version: 14.1
opatch: 'p28186730_1394219_Generic.zip'
opatch_version: 13.9.4.2.19
patch: 'p37732915_141100_Generic.zip'
patch_number: 37732915
napply: False
patch_folder: '37732915'
java_archive_file: jdk-8u451-linux-x64.tar.gz
java_version_path: 'jdk1.8.0_451'
