---
base_install_file: 'fmw_14.1.2.0.0_wls.jar'
weblogic_version: 14.1.2
opatch: 'p28186730_1394220_Generic.zip'
opatch_version: 13.9.4.2.20
patch: 'p38130086_141200_Generic.zip'
patch_number: 38130086
napply: False
patch_folder: '38130086'
java_archive_file: jdk-21.0.8_linux-x64_bin.tar.gz
java_version_path: 'jdk-21.0.8'
