---
# prereq installers
prereqs_installer_8: https://yum.oracle.com/repo/OracleLinux/OL8/appstream/x86_64/getPackage/oracle-ai-database-preinstall-26ai-1.0-1.el8.x86_64.rpm
prereqs_installer_9: https://yum.oracle.com/repo/OracleLinux/OL9/appstream/x86_64/getPackage/oracle-ai-database-preinstall-26ai-1.0-1.el9.x86_64.rpm
prereqs_installer: "{{ prereqs_installer_8 if ansible_distribution_major_version=='8' else prereqs_installer_9 }}"
# base installer values
base_version: 23.26.1.0.0
base_installer: oracle-ai-database-ee-26ai-1.0-1.el9.x86_64.rpm
# patch values
patch_filename: p39093711_230000_Linux-x86-64.zip
patch_number: 39093711  # used for directory
# opatch values
opatch_filename: p6880880_230000_Linux-x86-64.zip
opatch_version: 12.2.0.1.51
# jdk patch values
#jdk_patch_filename: p38245243_190000_Linux-x86-64.zip
#jdk_patch_number: 38245243 # used for directory
# 26ai specific configurations
oracle_family: "26ai"
sql_username: c##curam
