---
# path can be relative to download_url or local on controller
oracle_installer_path: "Oracle"

# Travis
travis_build: "{{ lookup('env', 'CI') }}"
travis_flags: "{{'-force -ignoresysprereqs -ignoreprereq' if lookup('env', 'CI') is defined else ''}}"

# Oracle config
oracle_version: 19.28.0.0.0
oracle_family: "{{ oracle_version.split('.') | first }}c"
oracle_base: /opt/oracle
oracle_home: "/opt/oracle/product/{{ oracle_family }}/dbhome_1"
oracle_inventory: /opt/Oracle/oraInventory  # only used for 12c
oracle_global_name: "orcl.{{ ansible_domain }}"
oracle_sid: orcl
oracle_admin_password: dummyPassword0
sql_username: curam
sql_password: dummyPassword0
enc_sql_password: dummyPassword0

# Bootstrap config
bootstrap_dateformat: 'dd MM yyyy'
bootstrap_dateseparator: '/'
bootstrap_dmx_locale: 'en_US'

# Common
profiled_path: /opt/profile.d

# Server info for downloading installers directly, leave undefined to copy installers from the controller
# download_url:   https://artifactory/repo
# download_header: { 'Authorization' : 'Basic <credentials>' }
