---
driver:
  name: docker
  provider:
    name: docker

lint: |
  set -e
  yamllint .

platforms:
  - name: rockylinux9
    image: rockylinux:9
    dockerfile: ../_resources/Dockerfile.j2
    pre_build_image: false
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    environment:
      container: docker

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      stderr_callback: debug
      stdout_callback: debug
  env:
    ANSIBLE_FORCE_COLOR: 'true'
  playbooks:
    converge: ./converge.yml
    verify: ./verify.yml
