---
- name: Verify
  hosts: all
  pre_tasks:
    - stat: "path=/opt/Props/Bootstrap.properties"
      register: boot_props
    - command: "db2level"
      become: true
      become_user: "db2admin"
      become_method: sudo
      become_flags: "-i"
      register: db2level_cmd

  tasks:
    - name: Check that Bootstrap.properties exists
      assert:
        that: boot_props.stat.exists
    - name: Check that the db2level command is working
      assert:
        that:
          - db2level_cmd.rc == 0
          - "'v12.1.2' in db2level_cmd.stdout"
