---
- name: Verify
  hosts: all
  pre_tasks:
    - name: include defaults
      include_vars: "../../roles/weblogic/defaults/main.yml"
    - name: include vars
      include_vars: "../../roles/weblogic/vars/v14.1.1.0.240922.yml"
    - stat:
        path: /opt/Props/AppServer.properties
      register: boot_props
    - name: Slurp profile.d
      slurp:
        src: /opt/profile.d/weblogic.sh
      register: env_oracle_sh
    - name: Slurp registry.xml
      slurp:
        src: /home/oracle/Oracle/Middleware/Oracle_Home/inventory/registry.xml
      register: registry_xml
    - name: Check OPatch version
      shell: "grep {{ opatch_version }} {{ weblogic_home }}/OPatch/version.txt"
      ignore_errors: True
      register: opatch_version_flag
      when: opatch_version is defined
    - name: Check if patched with correct patch
      become: yes
      become_user: "{{ weblogic_user }}"
      shell: "{{ weblogic_home }}/OPatch/opatch lspatches | grep -i {{ patch_number }}"
      changed_when: False
      when: patch_number is defined
  tasks:
    - name: Check that AppServer.properties exists
      assert:
        that: boot_props.stat.exists
    - name: Check that environment file has been created correctly
      assert:
        that: "{{ 'MW_HOME=/home/oracle/Oracle/Middleware/Oracle_Home' in (env_oracle_sh['content'] | b64decode) }}"
    - name: Check Weblogic Installed
      assert:
        that: "{{ 'distribution status=\"installed\" name=\"WebLogic Server\"' in (registry_xml['content'] | b64decode) }}"
    - name: Check OPatch version
      assert:
        that: opatch_version_flag.rc == 0
      when: opatch_version is defined
